services:
  app:
    build:
      context: ../../..
      dockerfile: ./src/infrastructure/docker/Dockerfile
    container_name: authcore_app
    networks:
      - authcore_network
    ports:
      - "${PORT_EXTERNAL}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      API_URL: ${API_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SECRET_CODE: ${SECRET_CODE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASS}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PORT: ${MYSQL_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    depends_on:
      - db
    volumes:
      - ../../../src:/usr/src/app/src
      - /usr/src/app/node_modules
      - /usr/src/app/.prisma

  db:
    image: mysql:8.0
    restart: always
    container_name: authcore_mysql_db
    networks:
      - authcore_network
    ports:
      - "${MYSQL_PORT_EXTERNAL}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:

networks:
  authcore_network:
